face:
  # true：允许多次注册 false：只能注册一次
  allowed-multiple-binding: true
  # ARC_SOFT_PRO 虹软（增值版）
  # BAIDU_OFFLINE：百度离线SDK
  # BAIDU_ONLINE：百度在线SDK
  # MEGVII：旷视
  api-name: BAIDU_OFFLINE
  #人脸图片本地保存路径
  file-path: D:/face
  # 虹软（增值版）
  arc-soft-pro:
    lib-path: D:/itlike/workSpace/Java/face/sdk/ArcSoft_ArcFacePro_windows_x64_java_V4.1/libs/WIN64
    # 离线激活文件(含后缀)
    active-file-path: D:/face/sdk/arcsoft/ArcSoft_ArcFacePro_windows_x64_java_V4.1/libs/WIN64/active_config.txt
    active-key: 86L1-11KF-7133-KUF4
    app-id: 3j8upsbqbrcZpqgvbKFZHDYJkzYk74h65G5KxJ3WqBRT
    sdk-key: A73GwQDShHH5vh5EJcEg8cnuqL82Bv2d6cZZwVerrvTW
    # 绑定得分阈值（0-100）
    binding-min-threshold: 80
    # 识别得分阈值（0-100）
    recognition-min-threshold: 80
    # 模糊度（0-1）0是最清晰，1是最模糊，推荐0.7
    blur: 0.7
  # 百度
  baidu-offline:
    lib-path: D:/itlike/workSpace/Java/face/sdk/Baidu_Face_Offline_SDK_Windows_Java_8.3/Baidu_Face_Offline_SDK_Windows_Java_8.3
    api-key: uftvVlqW7XQDvyAqEz4Mp6q3
    app-id: 25209037
    secret-key: SoCpMnb5LumIHz0OefCx8K1DmBEibHDG
    # 绑定得分阈值（0-100）
    binding-min-threshold: 80
    # 识别得分阈值（0-100）
    recognition-min-threshold: 80
    # 模糊度（0-1）0是最清晰，1是最模糊，推荐0.7
    blur: 0.7
  baidu-online:
    api-key: uftvVlqW7XQDvyAqEz4Mp6q3
    app-id: 25209037
    secret-key: SoCpMnb5LumIHz0OefCx8K1DmBEibHDG
    # 绑定得分阈值（0-100）
    binding-min-threshold: 80
    # 识别得分阈值（0-100）
    recognition-min-threshold: 80
    # 模糊度（0-1）0是最清晰，1是最模糊，推荐0.7
    blur: 0.7
  # 旷视
  megvii:
    api-key: uftvVlqW7XQDvyAqEz4Mp6q3
    app-id: 25209037
    secret-key: SoCpMnb5LumIHz0OefCx8K1DmBEibHDG
    # 绑定得分阈值（0-100）
    binding-min-threshold: 80
    # 识别得分阈值（0-100）
    recognition-min-threshold: 80
    # 模糊度（0-1）0是最清晰，1是最模糊，推荐0.7
    blur: 0.7
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${face.file-path}
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/face_dev?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 350000
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: true
        # 解决 Jpa In语句QueryPlanCache导致的JVM内存溢出
        query:
          # 限制缓存大小
          plan_cache_max_size: 64
          # 限制元数据大小
          plan_parameter_metadata_max_size: 32
          # 增加 IN 子句查询命中率
          in_clause_parameter_padding: ture
        #----end QueryPlanCache导致的JVM内存溢出-------
    show-sql: true



